uos-installer-servers/uos-installer-servers /usr/bin/
data/uos-installer-cli@.service  /usr/lib/systemd/system/
data/uos-installer-server.service /usr/lib/systemd/system/
data/uos-installer-start.service  /usr/lib/systemd/system/
data/installer-start /usr/bin
hooks /usr/share/uos-installer/
resources/packages_default.json  /usr/share/uos-installer/
resources/languages.json /usr/share/uos-installer/